### ISSUE TITLE
Artboard Error When Building via Game-CI and GitHub Actions

### ISSUE THREAD

**Issue by nekropants** [rive-app/rive-unity#74]
Hello, I'm running into this error when trying to make a CI build using GitHub actions. It's running on macOS. 

`Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at Rive.AssetImporter:loadEmbeddedAssetList <0x00007>
	  at Rive.AssetImporter:OnImportAsset <0x000f7>
	  at UnityEditor.AssetImporters.ScriptedImporter:GenerateAssetData <0x00027>
	  at <Module>:runtime_invoke_void__this___object <0x00073>
=================================================================
Obtained 28 stack frames.
#0  0x0000017bb5be10 in rive::Artboard::initialize()
#1  0x0000017bbd6ee8 in rive::File::read(rive::BinaryReader&, rive::RuntimeHeader const&)
#2  0x0000017bbd26e4 in rive::File::import(rive::Span<unsigned char const>, rive::Factory*, rive::ImportResult*, rive::FileAssetLoader*)
#3  0x0000017bad37c4 in loadEmbeddedAssetList
#4  0x00000179df9270 in  (wrapper managed-to-native) Rive.AssetImporter:loadEmbeddedAssetList (byte[],uintptr) [{0x1792c0ef8} + 0x80]  (0x179df91f0 0x179df92f8) [0x123b42a80 - Unity Child Domain]
#5  0x00000179df81e8 in  Rive.AssetImporter:OnImportAsset (UnityEditor.AssetImporters.AssetImportContext) [{0x126e70e70} + 0xf8] [./Library/PackageCache/app.rive.rive-unity@9c43422375/Editor/AssetImporter.cs :: 40u] (0x179df80f0 0x179df8870) [0x123b42a80 - Unity Child Domain]
#6  0x00000172358e90 in  UnityEditor.AssetImporters.ScriptedImporter:GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext) [{0x168892cc0} + 0x28] [/Users/bokken/build/output/unity/unity/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs :: 26u] (0x172358e68 0x172358ea0) [0x123b42a80 - Unity Child Domain]
#7  0x00000172358f14 in  (wrapper runtime-invoke) <Module>:runtime_invoke_void__this___object (object,intptr,intptr,intptr) [{0x33a953938} + 0x74]  (0x172358ea0 0x172358fb4) [0x123b42a80 - Unity Child Domain]`

**Comment by damzobridge** [comment]
Thanks for reporting this. We're looking into it. Which version of the package are you using?
